version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - .data/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
